#web: PLATFORM=web -r features/support -r features/web -r features/step_definitions -r features/web/pages
web: PLATFORM=web -r features/step_definitions -r features/support -r pages
html_report: --format progress --format html --out=test_results.html